Running soot scenario jdbi3;org.jdbi.jdbi3.Handle;query(String, Object);9f40c034b7d4b1a262f723ec81a630d1ebeb31bd
Running ConflictDetectionAlgorithm{name='Confluence Inter'}
Using jar at /home/victorlira/Documents/experiment/miningframework/output/files/jdbi3/9f40c034b7d4b1a262f723ec81a630d1ebeb31bd/original-without-dependencies/jdbi3-0.1-SNAPSHOT.jar
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/home/victorlira/Documents/experiment/miningframework/dependencies/soot-analysis-0.2.1-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Configure Soot Confluence 1 Inter 0,47700
Time to perform Confluence 1 Inter 0,55700
Configure Soot Confluence 2 Inter 0,17500
Time to perform Confluence 2 Inter 0,07900
Visited methods: 18
Depth limit: 5
CONFLICTS: [SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack10 = new org.jdbi.jdbi3.JDBIException,55,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,this := @this: org.jdbi.jdbi3.JDBIException,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l0 := @this: java.lang.RuntimeException,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1),96,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1),96,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause),7,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack9 := @caughtexception,45,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause),7,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack10 = new org.jdbi.jdbi3.JDBIException,55,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,this := @this: org.jdbi.jdbi3.JDBIException,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l0 := @this: java.lang.RuntimeException,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l0 := @this: java.lang.Exception,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l0 := @this: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l0.<java.lang.Throwable: java.lang.Throwable cause> = l1,312,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102) => (<java.lang.Throwable: void <init>(java.lang.Throwable)>, l0.<java.lang.Throwable: java.lang.Throwable cause> = l1, 312))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l0.<java.lang.Throwable: java.lang.Throwable cause> = l1,312,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102) => (<java.lang.Throwable: void <init>(java.lang.Throwable)>, l0.<java.lang.Throwable: java.lang.Throwable cause> = l1, 312)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,specialinvoke tmp$1952194564.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(stmt#2),64,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, specialinvoke tmp$1952194564.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(stmt#2), 64))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,specialinvoke tmp$1040493509.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(stmt#2),64,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, specialinvoke tmp$1040493509.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(stmt#2), 64)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1),102,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1),102,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack10 = new org.jdbi.jdbi3.JDBIException,55,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,this := @this: org.jdbi.jdbi3.JDBIException,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l0 := @this: java.lang.RuntimeException,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1),96,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1),96,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1),102,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack9 := @caughtexception,45,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1),102,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack10 = new org.jdbi.jdbi3.JDBIException,55,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,this := @this: org.jdbi.jdbi3.JDBIException,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l0 := @this: java.lang.RuntimeException,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1),96,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack9 := @caughtexception,45,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1),96,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause),7,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause),7,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1),102,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1),102,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause),7,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause),7,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack9 := @caughtexception,45,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,$stack5 = virtualinvoke l1.<java.lang.Throwable: java.lang.String toString()>(),311,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102) => (<java.lang.Throwable: void <init>(java.lang.Throwable)>, $stack5 = virtualinvoke l1.<java.lang.Throwable: java.lang.String toString()>(), 311))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack9 := @caughtexception,45,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,$stack5 = virtualinvoke l1.<java.lang.Throwable: java.lang.String toString()>(),311,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102) => (<java.lang.Throwable: void <init>(java.lang.Throwable)>, $stack5 = virtualinvoke l1.<java.lang.Throwable: java.lang.String toString()>(), 311)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack9 := @caughtexception,45,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,$stack5 = virtualinvoke l1.<java.lang.Throwable: java.lang.String toString()>(),311,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102) => (<java.lang.Throwable: void <init>(java.lang.Throwable)>, $stack5 = virtualinvoke l1.<java.lang.Throwable: java.lang.String toString()>(), 311))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,$stack5 = virtualinvoke l1.<java.lang.Throwable: java.lang.String toString()>(),311,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102) => (<java.lang.Throwable: void <init>(java.lang.Throwable)>, $stack5 = virtualinvoke l1.<java.lang.Throwable: java.lang.String toString()>(), 311)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack10 = new org.jdbi.jdbi3.JDBIException,55,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,this := @this: org.jdbi.jdbi3.JDBIException,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l0 := @this: java.lang.RuntimeException,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l0 := @this: java.lang.Exception,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l0 := @this: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l0.<java.lang.Throwable: java.lang.Throwable cause> = l1,312,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102) => (<java.lang.Throwable: void <init>(java.lang.Throwable)>, l0.<java.lang.Throwable: java.lang.Throwable cause> = l1, 312))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack9 := @caughtexception,45,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l0.<java.lang.Throwable: java.lang.Throwable cause> = l1,312,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102) => (<java.lang.Throwable: void <init>(java.lang.Throwable)>, l0.<java.lang.Throwable: java.lang.Throwable cause> = l1, 312)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack9 := @caughtexception,45,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,$stack5 = virtualinvoke l1.<java.lang.Throwable: java.lang.String toString()>(),311,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102) => (<java.lang.Throwable: void <init>(java.lang.Throwable)>, $stack5 = virtualinvoke l1.<java.lang.Throwable: java.lang.String toString()>(), 311))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,$stack5 = virtualinvoke l1.<java.lang.Throwable: java.lang.String toString()>(),311,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102) => (<java.lang.Throwable: void <init>(java.lang.Throwable)>, $stack5 = virtualinvoke l1.<java.lang.Throwable: java.lang.String toString()>(), 311)), SOURCE=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack10 = new org.jdbi.jdbi3.JDBIException,55,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,this := @this: org.jdbi.jdbi3.JDBIException,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l0 := @this: java.lang.RuntimeException,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l0 := @this: java.lang.Exception,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l0 := @this: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l0.<java.lang.Throwable: java.lang.Throwable cause> = l1,312,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102) => (<java.lang.Throwable: void <init>(java.lang.Throwable)>, l0.<java.lang.Throwable: java.lang.Throwable cause> = l1, 312))
SINK=>BASE: Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<java.lang.RuntimeException: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)) => Node(<java.lang.Exception: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l1 := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102)) => Node(<java.lang.Throwable: void <init>(java.lang.Throwable)>,l0.<java.lang.Throwable: java.lang.Throwable cause> = l1,312,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102) => (<java.lang.Throwable: void <init>(java.lang.Throwable)>, l0.<java.lang.Throwable: java.lang.Throwable cause> = l1, 312))]
Confluence interference in <org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>
Confluence flows from execution of lines 55 and 62 to line 55, defined in specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e) and stmt#2 = $stack11 and used in specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e)
Caused by line 55 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)
Caused by line 62 flow: path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)
Caused by line 55 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96)
Confluence interference in <org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>
Confluence flows from execution of lines 62 and 53 to line 55, defined in stmt#2 = $stack11 and e = $stack9 and used in specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e)
Caused by line 62 flow: path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)
Caused by line 53 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)
Caused by line 55 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)
Confluence interference in <org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>
Confluence flows from execution of lines 62 and 62 to line 64, defined in stmt#2 = $stack11 and stmt#2 = $stack11 and used in specialinvoke tmp$1040493509.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(stmt#2)
Caused by line 62 flow: path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)
Caused by line 62 flow: path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)
Caused by line 64 flow: path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, specialinvoke tmp$1040493509.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(stmt#2), 64)
Confluence interference in <org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>
Confluence flows from execution of lines 62 and 62 to line 62, defined in stmt#2 = $stack11 and stmt#2 = $stack11 and used in stmt#2 = $stack11
Caused by line 62 flow: path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)
Caused by line 62 flow: path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)
Caused by line 62 flow: path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)
Confluence interference in <org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>
Confluence flows from execution of lines 53 and 53 to line 55, defined in e = $stack9 and e = $stack9 and used in specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e)
Caused by line 53 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)
Caused by line 53 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)
Caused by line 55 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7) => (<java.lang.RuntimeException: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Exception: void <init>(java.lang.Throwable)>(l1), 96) => (<java.lang.Exception: void <init>(java.lang.Throwable)>, specialinvoke l0.<java.lang.Throwable: void <init>(java.lang.Throwable)>(l1), 102) => (<java.lang.Throwable: void <init>(java.lang.Throwable)>, $stack5 = virtualinvoke l1.<java.lang.Throwable: java.lang.String toString()>(), 311)
 Analysis results
----------------------------
 Number of conflicts: 17
 Results exported to out.txt
Error getting the previous content of the JSON file out.json
 JSON Results exported to out.json
----------------------------
Running ConflictDetectionAlgorithm{name='OA Inter'}
Using jar at /home/victorlira/Documents/experiment/miningframework/output/files/jdbi3/9f40c034b7d4b1a262f723ec81a630d1ebeb31bd/original-without-dependencies/jdbi3-0.1-SNAPSHOT.jar
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/home/victorlira/Documents/experiment/miningframework/dependencies/soot-analysis-0.2.1-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Depth limit: 5
Configure Soot OA Inter 0,59200
Runtime: 0.008s
OA interference in class Handle$1, method org.jdbi.jdbi3.ResultSetRow computeNext(), execution of line 45 overrides 45, assigning to variable this.<org.jdbi.jdbi3.ResultSetRow: java.sql.ResultSet rs>, 
Caused by line 45 flow:
at org.jdbi.jdbi3.Handle$1.computeNext(Handle$1.java:45)
at org.jdbi.jdbi3.ResultSetRow.<init>(ResultSetRow.java:12)
And line 45 flow:
at org.jdbi.jdbi3.Handle$1.computeNext(Handle$1.java:45)
at org.jdbi.jdbi3.ResultSetRow.<init>(ResultSetRow.java:12)
 
Time to perform OA Inter 0,67600
OA Inter Visited methods: 9
 Analysis results
----------------------------
 Number of conflicts: 3
 Results exported to out.txt
 JSON Results exported to out.json
----------------------------
Running left right NonCommutativeConflictDetectionAlgorithm{name = DFP-Inter}
Using jar at /home/victorlira/Documents/experiment/miningframework/output/files/jdbi3/9f40c034b7d4b1a262f723ec81a630d1ebeb31bd/original-without-dependencies/jdbi3-0.1-SNAPSHOT.jar
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/home/victorlira/Documents/experiment/miningframework/dependencies/soot-analysis-0.2.1-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Configure Soot DFP Inter 0,41500
Time to perform DFP Inter 0,43900
Depth limit: 5
CONFLICTS: DF interference in <org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>
Data flows from execution of line 53 to 53, defined in $stack9 := @caughtexception and propagated in e = $stack9
Caused by line 53 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)
Caused by line 53 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)
DF interference in <org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>
Data flows from execution of line 45 to 45, defined in $stack7 = new org.jdbi.jdbi3.ResultSetRow and propagated in specialinvoke this.<java.lang.Object: void <init>()>()
Caused by line 45 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack7.<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>($stack8), 45)
Caused by line 45 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack7.<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>($stack8), 45) => (<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>, specialinvoke this.<java.lang.Object: void <init>()>(), 10)
[List(Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack9 := @caughtexception,45,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53))), List(Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack7 = new org.jdbi.jdbi3.ResultSetRow,45,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack7.<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>($stack8), 45)) => Node(<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>,this := @this: org.jdbi.jdbi3.ResultSetRow,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack7.<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>($stack8), 45)) => Node(<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>,specialinvoke this.<java.lang.Object: void <init>()>(),10,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack7.<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>($stack8), 45) => (<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>, specialinvoke this.<java.lang.Object: void <init>()>(), 10)))]
Visited methods: 9
 Analysis results
----------------------------
 Number of conflicts: 2
 Results exported to out.txt
 JSON Results exported to out.json
----------------------------
Running right left NonCommutativeConflictDetectionAlgorithm{name = DFP-Inter}
Using jar at /home/victorlira/Documents/experiment/miningframework/output/files/jdbi3/9f40c034b7d4b1a262f723ec81a630d1ebeb31bd/original-without-dependencies/jdbi3-0.1-SNAPSHOT.jar
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/home/victorlira/Documents/experiment/miningframework/dependencies/soot-analysis-0.2.1-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Configure Soot DFP Inter 0,41300
Time to perform DFP Inter 0,48100
Depth limit: 5
CONFLICTS: DF interference in <org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>
Data flows from execution of line 53 to 55, defined in $stack9 := @caughtexception and propagated in specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e)
Caused by line 53 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)
Caused by line 55 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)
DF interference in <org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>
Data flows from execution of line 45 to 45, defined in $stack7 = new org.jdbi.jdbi3.ResultSetRow and propagated in specialinvoke this.<java.lang.Object: void <init>()>()
Caused by line 45 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack7.<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>($stack8), 45)
Caused by line 45 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack7.<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>($stack8), 45) => (<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>, specialinvoke this.<java.lang.Object: void <init>()>(), 10)
DF interference in <org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>
Data flows from execution of line 35 to 37, defined in rs = interfaceinvoke stmt.<java.sql.PreparedStatement: java.sql.ResultSet executeQuery()>() and propagated in specialinvoke tmp$79620878.<org.jdbi.jdbi3.Handle$1: void <init>(org.jdbi.jdbi3.Handle,java.sql.ResultSet)>(this, rs)
Caused by line 35 flow: path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, rs = interfaceinvoke stmt.<java.sql.PreparedStatement: java.sql.ResultSet executeQuery()>(), 35)
Caused by line 37 flow: path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, specialinvoke tmp$79620878.<org.jdbi.jdbi3.Handle$1: void <init>(org.jdbi.jdbi3.Handle,java.sql.ResultSet)>(this, rs), 37)
DF interference in <org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>
Data flows from execution of line 62 to 55, defined in $stack11 := @caughtexception and propagated in specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause)
Caused by line 62 flow: path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)
Caused by line 55 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)
DF interference in <org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>
Data flows from execution of line 53 to 55, defined in e = $stack9 and propagated in specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause)
Caused by line 53 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)
Caused by line 55 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)
DF interference in <org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>
Data flows from execution of line 53 to 55, defined in e = $stack9 and propagated in specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e)
Caused by line 53 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)
Caused by line 55 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)
DF interference in <org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>
Data flows from execution of line 35 to 37, defined in rs = interfaceinvoke stmt.<java.sql.PreparedStatement: java.sql.ResultSet executeQuery()>() and propagated in this.<org.jdbi.jdbi3.Handle$1: java.sql.ResultSet val$rs> = l2
Caused by line 35 flow: path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, rs = interfaceinvoke stmt.<java.sql.PreparedStatement: java.sql.ResultSet executeQuery()>(), 35)
Caused by line 37 flow: path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, specialinvoke tmp$79620878.<org.jdbi.jdbi3.Handle$1: void <init>(org.jdbi.jdbi3.Handle,java.sql.ResultSet)>(this, rs), 37) => (<org.jdbi.jdbi3.Handle$1: void <init>(org.jdbi.jdbi3.Handle,java.sql.ResultSet)>, this.<org.jdbi.jdbi3.Handle$1: java.sql.ResultSet val$rs> = l2, 38)
DF interference in <org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>
Data flows from execution of line 53 to 55, defined in $stack9 := @caughtexception and propagated in specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause)
Caused by line 53 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)
Caused by line 55 flow: path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7)
[List(Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack7 = new org.jdbi.jdbi3.ResultSetRow,45,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack7.<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>($stack8), 45)) => Node(<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>,this := @this: org.jdbi.jdbi3.ResultSetRow,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack7.<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>($stack8), 45)) => Node(<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>,specialinvoke this.<java.lang.Object: void <init>()>(),10,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack7.<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>($stack8), 45) => (<org.jdbi.jdbi3.ResultSetRow: void <init>(java.sql.ResultSet)>, specialinvoke this.<java.lang.Object: void <init>()>(), 10))), List(Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause),7,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7))), List(Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack9 := @caughtexception,45,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e),55,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55))), List(Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,rs = interfaceinvoke stmt.<java.sql.PreparedStatement: java.sql.ResultSet executeQuery()>(),35,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, rs = interfaceinvoke stmt.<java.sql.PreparedStatement: java.sql.ResultSet executeQuery()>(), 35)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,specialinvoke tmp$79620878.<org.jdbi.jdbi3.Handle$1: void <init>(org.jdbi.jdbi3.Handle,java.sql.ResultSet)>(this, rs),37,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, specialinvoke tmp$79620878.<org.jdbi.jdbi3.Handle$1: void <init>(org.jdbi.jdbi3.Handle,java.sql.ResultSet)>(this, rs), 37))), List(Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack9 := @caughtexception,45,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause),7,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7))), List(Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,$stack11 := @caughtexception,60,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,stmt#2 = $stack11,62,SimpleNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, stmt#2 = $stack11, 62)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,cause := @parameter0: java.lang.Throwable,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)) => Node(<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>,specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause),7,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55) => (<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>, specialinvoke this.<java.lang.RuntimeException: void <init>(java.lang.Throwable)>(cause), 7))), List(Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,rs = interfaceinvoke stmt.<java.sql.PreparedStatement: java.sql.ResultSet executeQuery()>(),35,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, rs = interfaceinvoke stmt.<java.sql.PreparedStatement: java.sql.ResultSet executeQuery()>(), 35)) => Node(<org.jdbi.jdbi3.Handle$1: void <init>(org.jdbi.jdbi3.Handle,java.sql.ResultSet)>,l2 := @parameter1: java.sql.ResultSet,-1,SimpleNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, specialinvoke tmp$79620878.<org.jdbi.jdbi3.Handle$1: void <init>(org.jdbi.jdbi3.Handle,java.sql.ResultSet)>(this, rs), 37)) => Node(<org.jdbi.jdbi3.Handle$1: void <init>(org.jdbi.jdbi3.Handle,java.sql.ResultSet)>,this.<org.jdbi.jdbi3.Handle$1: java.sql.ResultSet val$rs> = l2,38,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, specialinvoke tmp$79620878.<org.jdbi.jdbi3.Handle$1: void <init>(org.jdbi.jdbi3.Handle,java.sql.ResultSet)>(this, rs), 37) => (<org.jdbi.jdbi3.Handle$1: void <init>(org.jdbi.jdbi3.Handle,java.sql.ResultSet)>, this.<org.jdbi.jdbi3.Handle$1: java.sql.ResultSet val$rs> = l2, 38))), List(Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e),55,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55)))]
Visited methods: 9
 Analysis results
----------------------------
 Number of conflicts: 8
 Results exported to out.txt
 JSON Results exported to out.json
----------------------------
Running left right NonCommutativeConflictDetectionAlgorithm{name = PDG}
Using jar at /home/victorlira/Documents/experiment/miningframework/output/files/jdbi3/9f40c034b7d4b1a262f723ec81a630d1ebeb31bd/original-without-dependencies/jdbi3-0.1-SNAPSHOT.jar
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/home/victorlira/Documents/experiment/miningframework/dependencies/soot-analysis-0.2.1-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Configure Soot PDG 0,40900
Time to perform PDG 0,40400
CONFLICTS: [List(Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack9 := @caughtexception,45,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)))]
 Analysis results
----------------------------
 Number of conflicts: 1
 Results exported to out.txt
 JSON Results exported to out.json
----------------------------
Running right left NonCommutativeConflictDetectionAlgorithm{name = PDG}
Using jar at /home/victorlira/Documents/experiment/miningframework/output/files/jdbi3/9f40c034b7d4b1a262f723ec81a630d1ebeb31bd/original-without-dependencies/jdbi3-0.1-SNAPSHOT.jar
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions 1.7.x or earlier.
SLF4J: Ignoring binding found at [jar:file:/home/victorlira/Documents/experiment/miningframework/dependencies/soot-analysis-0.2.1-SNAPSHOT-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See https://www.slf4j.org/codes.html#ignoredBindings for an explanation.
Configure Soot PDG 0,58800
Time to perform PDG 0,45300
CONFLICTS: [List(Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e),55,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55))), List(Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,$stack9 := @caughtexception,45,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,e = $stack9,53,SourceNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, e = $stack9, 53)) => Node(<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>,specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e),55,SinkNode, path: (<org.jdbi.jdbi3.Handle$1: org.jdbi.jdbi3.ResultSetRow computeNext()>, specialinvoke $stack10.<org.jdbi.jdbi3.JDBIException: void <init>(java.lang.Throwable)>(e), 55))), List(Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,rs = interfaceinvoke stmt.<java.sql.PreparedStatement: java.sql.ResultSet executeQuery()>(),35,SourceNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, rs = interfaceinvoke stmt.<java.sql.PreparedStatement: java.sql.ResultSet executeQuery()>(), 35)) => Node(<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>,specialinvoke tmp$1810349933.<org.jdbi.jdbi3.Handle$1: void <init>(org.jdbi.jdbi3.Handle,java.sql.ResultSet)>(this, rs),37,SinkNode, path: (<org.jdbi.jdbi3.Handle: java.util.stream.Stream query(java.lang.String)>, specialinvoke tmp$1810349933.<org.jdbi.jdbi3.Handle$1: void <init>(org.jdbi.jdbi3.Handle,java.sql.ResultSet)>(this, rs), 37)))]
 Analysis results
----------------------------
 Number of conflicts: 3
 Results exported to out.txt
 JSON Results exported to out.json
----------------------------
